All:
	@echo "----------Building project:[ magieproject - Debug ]----------"
	@cd "magieproject" && $(MAKE) /nologo /f  "magieproject.mk"
clean:
	@echo "----------Cleaning project:[ magieproject - Debug ]----------"
	@cd "magieproject" && $(MAKE) /nologo /f  "magieproject.mk" clean
.PHONY: clean All

