.PHONY: clean All

All:
	@echo "----------Building project:[ RC4 - Debug ]----------"
	@"$(MAKE)" -f  "RC4.mk"
clean:
	@echo "----------Cleaning project:[ RC4 - Debug ]----------"
	@"$(MAKE)" -f  "RC4.mk" clean
